---

# config disks for swift object storage nodes
#
- name: format swift object disks
  command: mkfs.xfs -f /dev/{{ item.disk }}
  with_items: "{{ storage_node_disk_list }}"

- name: create swift object disks mount points
  shell: mkdir -p /srv/node/{{ item.disk }}
  with_items: "{{ storage_node_disk_list }}"

- name: add swift object disks fstab enitity
  shell: echo "/dev/{{ item.disk }}		/srv/node/{{ item.disk }}		xfs		noatime,nodiratime,nobarrier,logbufs=8 0 2" >> /etc/fstab
  with_items: "{{ storage_node_disk_list }}"

- name: mount swift object disks
  shell: mount /srv/node/{{ item.disk }}
  with_items: "{{ storage_node_disk_list }}"
