---

#
# Config and install swift 
#

- hosts:
  - proxy_node
  - storage_node

  roles:
  - swift_common

- hosts:
  - proxy_node

  roles:
  - swift_proxy

- hosts:
  - storage_node

  roles:
  - swift_storage

- hosts:
  - proxy_node
  - storage_node

  roles:
  
environment:
  http_proxy: http://web-proxy.sgp.hp.com:8080/
  
