---

#
# Install and config NTP server on target
#

- name: Install ntp package
  sudo: yes
  apt: pkg=ntp state=installed
  tags: ntp

# Optional

#- name: set timezone to UTC
  

- name: Config ntp server
  sudo: yes
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp

- name: Start the ntp service
  sudo: yes
  service: name=ntp state=restarted
  tags: ntp
  
