---

#
# Install ubuntu-cloud-keyring and clean the cache
#

- name: Install ubuntu-cloud-keyring
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - ubuntu-cloud-keyring
    - swift

- name: Clean the apt cache
  sudo: yes
  command: apt-get clean all

- name: Update the apt cache
  sudo: yes
  command: apt-get update 
