---

# config rsync for swift storage nodes
#
- name: config swift object rsyncd conf
  template: src=rsyncd.conf.j2 dest=/etc/rsyncd.conf


- name: config swift object default rsync
  lineinfile: dest=/etc/default/rsync state=present create=yes regexp=^RSYNC_ENABLE= line=RSYNC_ENABLE=true
  notify: restart rsync service

