---

# finalize the configuration of swift
- name: create swift conf file 
  template: src=swift.conf.j2 dest=/etc/swift/swift.conf

- name: ensure etc swift ownership
  shell: chown -R swift:swift /etc/swift
  notify: 
   - restart memcached
   - restart swift proxy
