---

#
# Create initial rings
#

- name: ensure /etc/swift exists
  file: path=/etc/swift state=directory


- name: Change to /etc/swift directory
  command: cd /etc/swift


# Create base ring builder file for account, container and object

- name: Create base ring builder file
  template: src={{ item }}-server.conf.j2 dest=/etc/swift/{{ item }}-server.conf
  with_items:
    - account
    - object
    - container


# Add each storage node to the account, container and object ring files

- name: Add each storage node to the ring files
  command:
  with_items:
    - account
    - object
    - container


# Distribute ring configuration files to storage nodes

- name: Distribute ring configuration files
  copy:
  with_items:
    - account
    - object
    - container

